# DWAPlannerROS:

# # Robot Configuration Parameters - Kobuki
#   max_vel_x: 0.5  # 0.55
#   min_vel_x: 0.0 

#   max_vel_y: 0.0  # diff drive robot
#   min_vel_y: 0.0  # diff drive robot

#   max_trans_vel: 0.3 # choose slightly less than the base's capability
#   min_trans_vel: 0.1  # this is the min trans velocity when there is negligible rotational velocity
#   trans_stopped_vel: 0.1

#   # Warning!
#   #   do not set min_trans_vel to 0.0 otherwise dwa will always think translational velocities
#   #   are non-negligible and small in place rotational velocities will be created.

#   max_rot_vel: 5.0  # choose slightly less than the base's capability
#   min_rot_vel: 0.4  # this is the min angular velocity when there is negligible translational velocity
#   rot_stopped_vel: 0.4
  
#   acc_lim_x: 0.5 # maximum is theoretically 2.0, but we 
#   acc_lim_theta: 2.0
#   acc_lim_y: 0.0      # diff drive robot

# # Goal Tolerance Parameters
#   yaw_goal_tolerance: 0.3  # 0.05
#   xy_goal_tolerance: 0.15  # 0.10
#   latch_xy_goal_tolerance: false

# # Forward Simulation Parameters
#   sim_time: 1.0       # 1.7
#   vx_samples: 15       # 3
#   vy_samples: 1       # diff drive robot, there is only one sample
#   vtheta_samples: 50  # 20

# # Trajectory Scoring Parameters
#   path_distance_bias: 64.0      # 32.0   - weighting for how much it should stick to the global path plan
#   goal_distance_bias: 24.0      # 24.0   - wighting for how much it should attempt to reach its goal
#   occdist_scale: 0.5            # 0.01   - weighting for how much the controller should avoid obstacles
#   forward_point_distance: 0.325 # 0.325  - how far along to place an additional scoring point
#   stop_time_buffer: 0.2         # 0.2    - amount of time a robot must stop in before colliding for a valid traj.
#   scaling_speed: 0.25           # 0.25   - absolute velocity at which to start scaling the robot's footprint
#   max_scaling_factor: 0.2       # 0.2    - how much to scale the robot's footprint when at speed.

# # Oscillation Prevention Parameters
#   oscillation_reset_dist: 0.05  # 0.05   - how far to travel before resetting oscillation flags

# # Debugging
#   publish_traj_pc : true
#   publish_cost_grid_pc: true
#   global_frame_id: odom


#   clearing_rotation_allowed: true
# # Differential-drive robot configuration - necessary?
# #  holonomic_robot: false

DWAPlannerROS:

# Robot Configuration Parameters - Kobuki
  max_vel_x: 0.15  # 0.55
  min_vel_x: 0.1 

  max_vel_y: 0.0  # diff drive robot
  min_vel_y: 0.0  # diff drive robot

  max_trans_vel: 0.1 # choose slightly less than the base's capability
  min_trans_vel: 0.1  # this is the min trans velocity when there is negligible rotational velocity
  trans_stopped_vel: 0.1

  # Warning!
  #   do not set min_trans_vel to 0.0 otherwise dwa will always think translational velocities
  #   are non-negligible and small in place rotational velocities will be created.

  max_rot_vel: 2.0  # choose slightly less than the base's capability
  min_rot_vel: 1.0  # this is the min angular velocity when there is negligible translational velocity
  rot_stopped_vel: 0.5
  
  acc_lim_x: 1.0 # maximum is theoretically 2.0, but we 
  acc_lim_theta: 2.0
  acc_lim_y: 0.0      # diff drive robot

# Goal Tolerance Parameters
  yaw_goal_tolerance: 0.15  # 0.05
  xy_goal_tolerance: 0.15  # 0.10
  latch_xy_goal_tolerance: true

# Forward Simulation Parameters
  sim_time: 1.0       # 1.7
  vx_samples: 20       # 3
  vy_samples: 1       # diff drive robot, there is only one sample
  vtheta_samples: 20  # 20

# Trajectory Scoring Parameters
  path_distance_bias: 64.0      # 32.0   - weighting for how much it should stick to the global path plan
  goal_distance_bias: 24.0      # 24.0   - wighting for how much it should attempt to reach its goal
  occdist_scale: 0.5            # 0.01   - weighting for how much the controller should avoid obstacles
  forward_point_distance: 0.325 # 0.325  - how far along to place an additional scoring point
  stop_time_buffer: 0.2         # 0.2    - amount of time a robot must stop in before colliding for a valid traj.
  scaling_speed: 0.25           # 0.25   - absolute velocity at which to start scaling the robot's footprint
  max_scaling_factor: 0.2       # 0.2    - how much to scale the robot's footprint when at speed.

# Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05  # 0.05   - how far to travel before resetting oscillation flags

# Debugging
  publish_traj_pc : true
  publish_cost_grid_pc: true
  global_frame_id: odom
  


# Differential-drive robot configuration - necessary?
#  holonomic_robot: false

TrajectoryPlannerROS:
   max_vel_x: 0.36
   min_vel_x: 0.2
   max_vel_y: 0.0  # zero for a differential drive robot
   min_vel_y: 0.0
   max_vel_theta: 0.7
   min_vel_theta: -0.7
   min_in_place_vel_theta: 0.5
   escape_vel: -0.15
   acc_lim_x: 0.3 # From test trials (0.304,0.285,0.26,0.365)
   acc_lim_y: 0.0 # zero for a differential drive robot
   acc_lim_theta: 1.0 #probably closer to 1.3 

   holonomic_robot: false
   yaw_goal_tolerance: 0.20 # about 12 degrees
   xy_goal_tolerance: 0.2  # 20 cm
   latch_xy_goal_tolerance: true
   pdist_scale: 0.6
   gdist_scale: 0.7
   meter_scoring: true

   heading_lookahead: 0.375

   heading_scoring: false
   heading_scoring_timestep: 0.8
   occdist_scale: 0.01
   oscillation_reset_dist: 0.05
   publish_cost_grid_pc: false
   prune_plan: true

   #sim_time: 4
   sim_granularity: 0.025
   angular_sim_granularity: 0.025
   vx_samples: 28
   vy_samples: 0 # zero for a differential drive robot
   vtheta_samples: 40
   dwa: true
   simple_attractor: false