local_costmap:
   global_frame: map
   robot_base_frame: base_link
   update_frequency: 5.0
   publish_frequency: 2.0
   static_map: false
   rolling_window: true
   always_send_full_costmap: true
   width: 4.0
   height: 4.0
   resolution: 0.01
   transform_tolerance: 0.5
   map_type: costmap
   plugins:
    - {name: static_layer,            type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,      type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}